// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcyDVnBqHdiyliEDYJfq3lF-SNpamvx-U',
    appId: '1:791849734815:web:a444086304218ec15308aa',
    messagingSenderId: '791849734815',
    projectId: 'rxdart-learning-phonecontact',
    authDomain: 'rxdart-learning-phonecontact.firebaseapp.com',
    storageBucket: 'rxdart-learning-phonecontact.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQvQ8aotAYjcrfgPhsfcNA-pKUUpiUTqQ',
    appId: '1:791849734815:android:d8295c60004ea34e5308aa',
    messagingSenderId: '791849734815',
    projectId: 'rxdart-learning-phonecontact',
    storageBucket: 'rxdart-learning-phonecontact.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpbu3nWrE6DB6akWfSVxfwVPhYbVU2MQQ',
    appId: '1:791849734815:ios:2f253a0b6171c75e5308aa',
    messagingSenderId: '791849734815',
    projectId: 'rxdart-learning-phonecontact',
    storageBucket: 'rxdart-learning-phonecontact.appspot.com',
    iosBundleId: 'com.example.rxDartPhonebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpbu3nWrE6DB6akWfSVxfwVPhYbVU2MQQ',
    appId: '1:791849734815:ios:b42529561a3cd9825308aa',
    messagingSenderId: '791849734815',
    projectId: 'rxdart-learning-phonecontact',
    storageBucket: 'rxdart-learning-phonecontact.appspot.com',
    iosBundleId: 'com.example.rxDartPhonebook.RunnerTests',
  );
}
